name: In-game Bug Report
description: Melaporkan bug yang ada di server Luxinity Roleplay
title: "[In-game Bug Report] "
labels: ["ingame", "bug"]
assignees: 
  - Abielfrl
  - Azharhrj

body:
  - type: markdown
    attributes: 
      value: |
        Pelaporan bug diharuskan sedetail mungkin, agar developer tidak kesulitan saat mereproduksinya.
  - type: input
    id: nama-ucp
    attributes:
      label: Nama UCP
      description: Tulis nama UCP kamu
      placeholder: 'Contoh: Firpanpus'
    validations:
      required: true
  - type: textarea
    id: deskripsi-bug
    attributes:
      label: Deskripsi Bug
      description: Jelaskan secara rinci bug apa yang kamu temukan di server Luxinity Roleplay
      placeholder: 'Contoh: Terdapat obyek yang melayang di area East Beach'
    validations:
      required: true
  - type: textarea
    id: bug-reproduce
    attributes:
      label: Langkah reproduksi bug
      description: Jelaskan langkah-langkah bagaimana bug tersebut bisa terjadi
      placeholder: |
        *Contoh melaporkan langkah untuk mereproduksi bug yang kamu alami*:
        1. Pergi ke '...'
        2. Ketik '...'
        3. Naik kendaraan '...'
    validations:
      required: true
  - type: textarea
    id: bug-proof
    attributes:
      label: Barang bukti
      description: Jika ada, kirimkan barang bukti di bawah. Barang bukti bisa berupa screenshot/video
      placeholder: |
        Chatlog:
        ```
        [00:00:01] Andreas_Ayonima says: azhar pepek kontol memek
        [00:16:10] Server closed the connection
        ```
        
        Video (Recommended):
        https://youtube.com or equivalent
        
        Screnshot:
        https://imgur.com or equivalent
    validations:
      required: false
  - type: textarea
    id: more-info
    attributes:
      label: Info tambahan
      description: Informasi tambahan yang relevan tentang bug yang kamu alami
      placeholder: 'Contoh: seharusnya bug ini tidak terjadi pada versi sebelumnya.'
    validations:
      required: false
 
